<a href="https://colab.research.google.com/github/KyeongHoSeong/rl_studios/blob/main/001_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 ref: https://wikidocs.net/53560
1. 데이터에 대한 이해(Data Definition)
  1. 훈련 데이터셋과 테스트 데이터셋
  2. 훈련 데이터셋의 구성
      x_train = torch.FloatTensor([[1], [2], [3]])
      y_train = torch.FloatTensor([[2], [4], [6]])

2. 가설(Hypothesis) 수립
    H(x)=Wx+b

3. 비용 함수(Cost function)에 대한 이해
  비용 함수(cost function) = 손실 함수(loss function) = 오차 함수(error function) = 목적 함수(objective function)

4. 옵티마이저 - 경사 하강법(Gradient Descent)


In [18]:
import torch.nn as nn
# model = nn.Linear(input_dim, output_dim)

# 파이토치로 선형 회귀 구현하기

1. import

In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

2. 변수 선언
훈련 데이터인 x_train과 y_train을 선언

In [20]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

print(x_train)
print(x_train.shape)

print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


3. 가중치와 편향의 초기화
선형 회귀란 학습 데이터와 가장 잘 맞는 하나의 직선을 찾는 일입니다.
그리고 가장 잘 맞는 직선을 정의하는 것은 바로 W와 b입니다.
선형 회귀의 목표는 가장 잘 맞는 직선을 정의하는 W와 b의 값을 찾는 것입니다.

In [21]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True) 
# 가중치 W를 출력
print(W) 

tensor([0.], requires_grad=True)


In [22]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


현재 가중치 W와 b 둘 다 0이므로 현 직선의 방정식은 다음과 같습니다.
y=0×x+0

4. 가설 세우기

H(x)=Wx+b

In [23]:
hypothesis = W * x_train + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


5. 비용 함수 선언하기

평균 제곱 오차를 선언
cost(W,b)=1n∑i=1n[y(i)−H(x(i))]2

In [24]:
cost= torch.mean(hypothesis - y_train) ** 2
print(cost)

tensor(16., grad_fn=<PowBackward0>)


6. 경사 하강법 구현하기
lr은 학습률(learning rate)
학습 대상인 W와 b가 SGD의 입력


In [25]:
optimizer = optim.SGD([W,b], lr=0.01)

# # gradient를 0으로 초기화
optimizer.zero_grad() 
# 비용 함수를 미분하여 gradient 계산
cost.backward() 
# W와 b를 업데이트
optimizer.step() 



7. 출력

In [26]:
nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.329, b: 0.152 Cost: 15.217067
Epoch  100/1999 W: 1.743, b: 0.584 Cost: 0.049229
Epoch  200/1999 W: 1.798, b: 0.459 Cost: 0.030421
Epoch  300/1999 W: 1.841, b: 0.361 Cost: 0.018798
Epoch  400/1999 W: 1.875, b: 0.284 Cost: 0.011616
Epoch  500/1999 W: 1.902, b: 0.223 Cost: 0.007178
Epoch  600/1999 W: 1.923, b: 0.175 Cost: 0.004436
Epoch  700/1999 W: 1.939, b: 0.138 Cost: 0.002741
Epoch  800/1999 W: 1.952, b: 0.108 Cost: 0.001694
Epoch  900/1999 W: 1.963, b: 0.085 Cost: 0.001047
Epoch 1000/1999 W: 1.971, b: 0.067 Cost: 0.000647
Epoch 1100/1999 W: 1.977, b: 0.053 Cost: 0.000400
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000247
Epoch 1300/1999 W: 1.986, b: 0.033 Cost: 0.000153
Epoch 1400/1999 W: 1.989, b: 0.026 Cost: 0.000094
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000058
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000036
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000014
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

# Tip: optimizer.zero_grad()가 필요한 이유
## 파이토치는 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적

In [27]:
import torch
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

  z = 2*w

  z.backward()
  print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


# Tip: torch.manual_seed()를 하는 이유
torch.manual_seed()를 사용한 프로그램의 결과는 다른 컴퓨터에서 실행시켜도 동일한 결과를 얻을 수 있습니다. 그 이유는 torch.manual_seed()는 난수 발생 순서와 값을 동일하게 보장해준다는 특징때문입니다. 우선 랜덤 시드가 3일 때 두 번 난수를 발생시켜보고, 다른 랜덤 시드를 사용한 후에 다시 랜덤 시드를 3을 사용한다면 난수 발생값이 동일하게 나오는지 보겠습니다.

In [28]:
import torch

torch.manual_seed(3)
print('랜덤 시드가 3일 때')
for i in range(1,3):
  print(torch.rand(1))

랜덤 시드가 3일 때
tensor([0.0043])
tensor([0.1056])


In [29]:
torch.manual_seed(5)
print('랜덤 시드가 5일 때')
for i in range(1,3):
  print(torch.rand(1))

랜덤 시드가 5일 때
tensor([0.8303])
tensor([0.1261])


In [30]:
torch.manual_seed(3)
print('랜덤 시드가 다시 3일 때')
for i in range(1,3):
  print(torch.rand(1))

랜덤 시드가 다시 3일 때
tensor([0.0043])
tensor([0.1056])


# Tip3:  requires_grad
텐서에는 requires_grad라는 속성이 있습니다. 이것을 True로 설정하면 자동 미분 기능이 적용됩니다. 선형 회귀부터 신경망과 같은 복잡한 구조에서 파라미터들이 모두 이 기능이 적용됩니다. requires_grad = True가 적용된 텐서에 연산을 하면, 계산 그래프가 생성되며 backward 함수를 호출하면 그래프로부터 자동으로 미분이 계산됩니다.