<a href="https://colab.research.google.com/github/KyeongHoSeong/rl_studios/blob/main/001_linear_regression_multivariable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Reference: [PyTorch로 시작하는 딥 러닝 입문-3.2]-(https://wikidocs.net/54841) 

# 다중 선형 회귀(Multivariable Linear regression)

1. 데이터에 대한 이해(Data Definition)

H(x)=w1x1+w2x2+w3x3+b

In [27]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

2. 구현

In [28]:
torch.manual_seed(1)

# 훈련 데이터
# Input 변수 3개, Out: 1
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# weight, biase
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimzier
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

epoches = 1000
for epoch in range(epoches+1):
    # model 정의
    hypothesis = w1* x1_train + w2* x2_train + w3* x3_train + b

    # loss
    loss = torch.mean(hypothesis - y_train) ** 2

    # loss로 H(x) opte
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, epoches, w1.item(), w2.item(), w3.item(), b.item(), loss.item()
        ))

Epoch    0/1000 w1: 0.290 w2: 0.289 w3: 0.293 b: 0.003 Cost: 29241.000000
Epoch  100/1000 w1: 0.669 w2: 0.667 w3: 0.675 b: 0.008 Cost: 0.000000
Epoch  200/1000 w1: 0.669 w2: 0.667 w3: 0.675 b: 0.008 Cost: 0.000000
Epoch  300/1000 w1: 0.669 w2: 0.667 w3: 0.675 b: 0.008 Cost: 0.000000
Epoch  400/1000 w1: 0.669 w2: 0.667 w3: 0.675 b: 0.008 Cost: 0.000000
Epoch  500/1000 w1: 0.669 w2: 0.667 w3: 0.675 b: 0.008 Cost: 0.000000
Epoch  600/1000 w1: 0.669 w2: 0.667 w3: 0.675 b: 0.008 Cost: 0.000000
Epoch  700/1000 w1: 0.669 w2: 0.667 w3: 0.675 b: 0.008 Cost: 0.000000
Epoch  800/1000 w1: 0.669 w2: 0.667 w3: 0.675 b: 0.008 Cost: 0.000000
Epoch  900/1000 w1: 0.669 w2: 0.667 w3: 0.675 b: 0.008 Cost: 0.000000
Epoch 1000/1000 w1: 0.669 w2: 0.667 w3: 0.675 b: 0.008 Cost: 0.000000


3. 벡터와 행렬 연산으로 개선하기

* 개선 전: x1_train, x2_train, x3_train와 w1, w2, w3를 일일히 선언 
* 개선 후: 행력 Dot Product
  * (x1 x2 x3)
  * (w1 w2 w3)
  * x * w = (w1x1 + w2x2 + w3x3
  * H(X) = XW

4. 행렬 연산으로 다중 선형 회귀 구현하기

In [29]:
# 1. 훈련 데이터 설정
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

print(x_train)
print(y_train)

print(x_train.shape)
print(y_train.shape)

tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  80.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.]])
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]])
torch.Size([5, 3])
torch.Size([5, 1])


In [30]:
# 2. weight W와 bias 선언 
W = torch.zeros((3, 1), requires_grad=True) # 3 X 1 <= x_train (5 3) x (3 1) = (5 1) = y train(5, 1)
b = torch.zeros(1, requires_grad=True)

In [31]:
# 3. 모델 정의
hypothesis = x_train.matmul(W) + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [32]:
# 4. optimizer = optim.
optimizer = optim.SGD([W,b], lr=13-5)

In [35]:
# 5. training
epoches = 2000
for epoch in range(epoches + 1):

  # H(x) 
  hypothesis = x_train.matmul(W) + b

  # cost
  cost = torch.mean(hypothesis - y_train) ** 2

  #optim
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # 100번마다 로그 출력
  if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, epoches, w1.item(), w2.item(), w3.item(), b.item(), loss.item()
        ))

  # print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
  #       epoch, epoches, hypothesis.squeeze().detach(), cost.item()
  #   ))


Epoch    0/2000 w1: 0.669 w2: 0.667 w3: 0.675 b: nan Cost: 0.000000
Epoch  100/2000 w1: 0.669 w2: 0.667 w3: 0.675 b: nan Cost: 0.000000
Epoch  200/2000 w1: 0.669 w2: 0.667 w3: 0.675 b: nan Cost: 0.000000
Epoch  300/2000 w1: 0.669 w2: 0.667 w3: 0.675 b: nan Cost: 0.000000
Epoch  400/2000 w1: 0.669 w2: 0.667 w3: 0.675 b: nan Cost: 0.000000
Epoch  500/2000 w1: 0.669 w2: 0.667 w3: 0.675 b: nan Cost: 0.000000
Epoch  600/2000 w1: 0.669 w2: 0.667 w3: 0.675 b: nan Cost: 0.000000
Epoch  700/2000 w1: 0.669 w2: 0.667 w3: 0.675 b: nan Cost: 0.000000
Epoch  800/2000 w1: 0.669 w2: 0.667 w3: 0.675 b: nan Cost: 0.000000
Epoch  900/2000 w1: 0.669 w2: 0.667 w3: 0.675 b: nan Cost: 0.000000
Epoch 1000/2000 w1: 0.669 w2: 0.667 w3: 0.675 b: nan Cost: 0.000000
Epoch 1100/2000 w1: 0.669 w2: 0.667 w3: 0.675 b: nan Cost: 0.000000
Epoch 1200/2000 w1: 0.669 w2: 0.667 w3: 0.675 b: nan Cost: 0.000000
Epoch 1300/2000 w1: 0.669 w2: 0.667 w3: 0.675 b: nan Cost: 0.000000
Epoch 1400/2000 w1: 0.669 w2: 0.667 w3: 0.675 b: