<a href="https://colab.research.google.com/github/KyeongHoSeong/rl_studios/blob/main/001_04_linear_regression_torch_nn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Reference: [PyTorch로 시작하는 딥 러닝 입문-3.2]-(https://wikidocs.net/55409) 

# Linear regression with nn model

파이토치에서 이미 구현되어져 제공되고 있는 함수들을 불러오는 것으로 더 쉽게 선형 회귀 모델을 구현

* 선형 회귀 모델: nn.Linear()
* 평균 제곱오차: nn.functional.mse_loss()

    import torch.nn as nn
    model = nn.Linear(input_dim, output_dim)

    import torch.nn.functional as F
    cost = F.mse_loss(prediction, y_train)


1. 단순 선형 회귀 구현하기



In [37]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

# data : y = 2x 
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

2. 선형 회기 모델 구현

nn.Linear()는 입력의 차원, 출력의 차원을 인수로 사용

In [39]:
# 모델을 선언 및 초기화. 
# 단순 선형 회귀이므로 input_dim=1, output_dim=1.
model = nn.Linear(1,1)

#model에는 가중치 W와 편향 b가 저장되어져 있다.
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]


3. optimizer 정의


In [40]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

4. 훈련



In [44]:
epoches = 2000

for epoch in range(epoches):
  # H(x)
  prediction = model(x_train)

  # cost
  cost= F.mse_loss(prediction, y_train)

  # cost로 H(x) 개선하는 부분
  # gradient를 0으로 초기화
  optimizer.zero_grad()

  # 비용 함수를 미분하여 gradient 계산
  cost.backward()
  
  # W와 b를 업데이트
  optimizer.step()

  if epoch % 100 == 0:
    # 100번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, epoches, cost.item()
      ))


Epoch    0/2000 Cost: 11.673522
Epoch  100/2000 Cost: 0.126824
Epoch  200/2000 Cost: 0.078370
Epoch  300/2000 Cost: 0.048428
Epoch  400/2000 Cost: 0.029925
Epoch  500/2000 Cost: 0.018492
Epoch  600/2000 Cost: 0.011427
Epoch  700/2000 Cost: 0.007061
Epoch  800/2000 Cost: 0.004363
Epoch  900/2000 Cost: 0.002696
Epoch 1000/2000 Cost: 0.001666
Epoch 1100/2000 Cost: 0.001030
Epoch 1200/2000 Cost: 0.000636
Epoch 1300/2000 Cost: 0.000393
Epoch 1400/2000 Cost: 0.000243
Epoch 1500/2000 Cost: 0.000150
Epoch 1600/2000 Cost: 0.000093
Epoch 1700/2000 Cost: 0.000057
Epoch 1800/2000 Cost: 0.000035
Epoch 1900/2000 Cost: 0.000022


5. Test


In [45]:
# 임의의 입력 4를 선언
new_var =  torch.FloatTensor([[4.0]]) 

# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward 연산

# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값 :", pred_y) 

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9926]], grad_fn=<AddmmBackward>)


6. Verify w. b


In [46]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9957]], requires_grad=True), Parameter containing:
tensor([0.0097], requires_grad=True)]


# 2. 다중 선형 회귀 구현하기

목표: 
1. 3개의 입력데이터 1개의 출력데이터에 대하여 
2. H(x)=w1x1+w2x2+w3x3+b를 구하고
3. 테스트 데이터로 예측 



In [54]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [48]:
torch.manual_seed(1)

1. 데이터 선언

H(x)=w1x1+w2x2+w3x3+b

In [55]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

2. 모델 구현


In [56]:
#  input_dim=3, output_dim=1.
model = nn.Linear(3,1)

print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.0803, -0.0707,  0.1601]], requires_grad=True), Parameter containing:
tensor([0.0285], requires_grad=True)]


3. define Optimizer 

model.parameters()를 사용하여 3개의 w와 b를 전달

In [57]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

4. 훈련

In [59]:
epoches = 2000

for epoch in range(epoches):

  prediction = model(x_train)

  cost = F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, epoches, cost.item()
      ))

Epoch    0/2000 Cost: 7780.782715
Epoch  100/2000 Cost: 0.848898
Epoch  200/2000 Cost: 0.825364
Epoch  300/2000 Cost: 0.803000
Epoch  400/2000 Cost: 0.781752
Epoch  500/2000 Cost: 0.761585
Epoch  600/2000 Cost: 0.742406
Epoch  700/2000 Cost: 0.724176
Epoch  800/2000 Cost: 0.706855
Epoch  900/2000 Cost: 0.690388
Epoch 1000/2000 Cost: 0.674727
Epoch 1100/2000 Cost: 0.659842
Epoch 1200/2000 Cost: 0.645690
Epoch 1300/2000 Cost: 0.632208
Epoch 1400/2000 Cost: 0.619392
Epoch 1500/2000 Cost: 0.607186
Epoch 1600/2000 Cost: 0.595576
Epoch 1700/2000 Cost: 0.584520
Epoch 1800/2000 Cost: 0.573982
Epoch 1900/2000 Cost: 0.563946


5. Test

In [60]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.6526]], grad_fn=<AddmmBackward>)


6. 검증

In [61]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.7497, 0.4868, 0.7725]], requires_grad=True), Parameter containing:
tensor([0.0386], requires_grad=True)]
